import Sidebar from "@/components/Sidebar";
import "@/app/global.css";
import { Inter } from "next/font/google";
import Provider from "@/components/Provider";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Provider>
          {/* <Sidebar /> */}
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
